### PR TITLE
es5 changes

### PR DESCRIPTION
**Pull request by steveslayden**
Remove es6 constructs to allow support for older node engines (>= 0.10.0).

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Do we need to update the `package.json:engines` field now that we can support down to `0.10`?

**Comment by steveslayden** [comment]
Ah, yes, good catch. Jason is doing most of the work. I think he's targeting 12, though. Is that right, Jason?

**Comment by ryan-roemer** [comment]
Overgeneralizing a little bit, anything that we do for `0.12` should also work for `0.10` (unless we're using newer `fs.*` methods that aren't in `0.10`)

I vote for just going for `0.10` in engines restriction and CI unless it's painful, and if so, then look to `0.12`...

**Comment by steveslayden** [comment]
I see, good point.

**Comment by jasonwilson** [comment]
We should aim for 0.10.0 if possible. I don't foresee any features requiring anything newer. We can close this: https://github.com/FormidableLabs/nodejs-dashboard/pull/41 as well.

**Comment by steveslayden** [comment]
Fiy, I downgraded to node .10.0. Had to downgrade to npm 1.4.28 too. Works fine, but getting error in eslint package. Looking into it...

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 2, 2016 at 5:37 PM, Jason Wilson<notifications@github.com> wrote:   
We should aim for 0.10.0 if possible. I don't foresee any features requiring anything newer. We can close this: #41 as well.

**Comment by jasonwilson** [comment]
Forgot to mention @steveslayden, we might want to downgrade this to es5: https://github.com/FormidableLabs/nodejs-dashboard/blob/master/.eslintrc#L3

**Comment by steveslayden** [comment]
Gotcha, np

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 2, 2016 at 6:00 PM, Jason Wilson<notifications@github.com> wrote:   
Forgot to mention @steveslayden, we might want to downgrade this to es5: https://github.com/FormidableLabs/nodejs-dashboard/blob/master/.eslintrc#L3

**Comment by steveslayden** [comment]
FYI, I updated the minimum node version to 0.10.0 and tested (had to downgrade to npm to 1.4.28 also) and everything looks good. Looks like you had already switched the .eslintrc from node-e6 to node-e5.

**Pull request merged**
