### PR TITLE
Features/goto time index

### PR DESCRIPTION
**Pull request by mscottx88**
This one adds a popup to allow the user to enter a specific time index they would like to view in the graphs.

### CODE REVIEW

**Comment by mscottx88** [comment]
@jasonwilson @ryan-roemer @aisapatino Hi there, this is the next PR for Node Dashboard.  In this PR, a popup can be activated, which allows the user to enter a desired time value and the historical graphs will position the view there.

**Comment by ryan-roemer** [comment]
Nice work! Could we get some unit tests for the new view / additional functionality?

**Comment by mscottx88** [comment]
@ryan-roemer Absolutely :) I will begin adding those tomorrow!

**Comment by mscottx88** [comment]
@ryan-roemer I've added code coverage for that new view and learned a couple things along the way.  Notably, how to simulate a keystroke programmatically in blessed.

**Pull request merged**
